return {
  --   {
  --     "mxsdev/nvim-dap-vscode-js",
  --     dependencies = { "mfussenegger/nvim-dap" },
  --   },
  --   {
  --     "microsoft/vscode-js-debug",
  --     build = "npm install --legacy-peer-deps && npx gulp vsDebugServerBundle && mv dist out",
  --   },
  --   {
  --     "jay-babu/mason-nvim-dap.nvim",
  --     dependencies = "mason.nvim",
  --     cmd = { "DapInstall", "DapUninstall" },
  --     opts = {
  --       -- reasonable debug configurations
  --       automatic_installation = true,
  --
  --       -- You can provide additional configuration to the handlers,
  --       -- see mason-nvim-dap README for more information
  --       handlers = {},
  --
  --       -- You'll need to check that you have the required things installed
  --       -- online, please don't ask me how to install them :)
  --       ensure_installed = {
  --         -- Update this to ensure that you have the debuggers for the langs you want
  --         "python",
  --         "chrome",
  --       },
  --     },
  --     -- mason-nvim-dap is loaded when nvim-dap loads
  --     config = function() end,
  --   },
}
